apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  source:
    repoURL: https://github.com/david-wirelab/argocd-kubernetes-test.git
    targetRevision: HEAD
    path: kube
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-test
